name: Android Debug CI

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: List files in build directory
        run: ls -la app/build/outputs/apk/debug/

      - name: Rename APK file
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/vacation-vibes-${{ github.event.release.tag_name }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vacation-vibes-${{ github.event.release.tag_name }}.apk
          path: app/build/outputs/apk/debug/vacation-vibes-${{ github.event.release.tag_name }}.apk

      - name: Upload APK as release asset
        run: gh release upload ${{ github.event.release.tag_name }} app/build/outputs/apk/debug/vacation-vibes-${{ github.event.release.tag_name }}.apk --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
